version: '3.7'
services:
  bot:
    build: .
    volumes:
      - ./:/deliverydetect/
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:7.2.4
    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_DATABASES: 16
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./db/:/var/lib/redis/
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
