"""empty message

Revision ID: 7731860a945e
Revises: 838cad68caba
Create Date: 2024-07-04 21:44:27.170643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7731860a945e"
down_revision: Union[str, None] = "838cad68caba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courier", sa.Column("telegram_id", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courier", "telegram_id")
    # ### end Alembic commands ###
